remote_theme: jekyll/minima@bf9ef989246b63536e9db61082f663f1a6d4d9ce
description: All things about protocol specification, testing, and verification. Creative Commons Attribution 4.0 International License.
show_downloads: false
github.is_project_page: false
google_analytics: G-98E1SLS4S5
domain: protocols-made-fun.com
url: https://protocols-made-fun.com
baseurl:
twitter_username: k0nn0v
github_username:  konnov
disqus:
  shortname: protocols-made-fun
author:
  igor:
    name: Igor Konnov
    url: https://konnov.phd
    email: "igor@konnov.phd"
title: Protocols Made Fun
minima:
  skin: auto
  nav_pages:
    - about.md
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
# https://docs.github.com/en/enterprise-cloud@latest/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#syntax-highlighting
kramdown:
  syntax_highlighter_opts:
    disable : true
exclude:
  - _scripts
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
